language: python
python:
  - '3.7'
dist: bionic

before_install:
  - git clone https://github.com/ait-aecid/aminer-ansible.git roles/aminer
  - git clone https://github.com/ait-aecid/logdata-anomaly-miner
  - cd logdata-anomaly-miner
  - git checkout development
  - cd ..
  - sed -e "s+{{SOURCEDIR}}+$PWD/logdata-anomaly-miner+g" $PWD/logdata-anomaly-miner/.playbook.yml > playbook.yml

install:
  - sudo apt-get update -y
  - sudo apt-get install -y exim4 procps cpulimit mailutils ansible
  - sudo ansible-playbook playbook.yml
  - sudo pip3 install coverage
  - sudo pip3 install fastapi
  - sudo pip3 install passlib[bcrypt]
  - sudo pip3 install python-jose
  - sudo pip3 install python-multipart
  - sudo chmod +x runUnittests.sh
  - sudo chmod +x runCoverageTests.sh

script:
  - ./runUnittests.sh
  - ./runCoverageTests.sh
