language: python
python:
  - '3.7'
dist: bionic

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y exim4 procps cpulimit ansible mailutils python3-pip python3-kafka # Todo remove unneeded
  - git clone https://github.com/ait-aecid/aminer-ansible.git roles/aminer
  - git clone https://github.com/ait-aecid/aminer-rest.git
  - ln -s $PWD/source/root/usr/lib/logdata-anomaly-miner/AMinerRemoteControl $PWD/aminer-rest/AMinerRemoteControl
  - sed -e "s+{{SOURCEDIR}}+$PWD+g" .playbook.yml > playbook.yml

install:
  - sudo pip3 install coverage
  - sudo ansible-playbook playbook.yml
  - sudo chmod +x runUnittests.sh
  - sudo chmod +x runCoverageTests.sh

script:
  - ./runUnittests.sh

after_script:
  - rm $PWD/aminer-rest/AMinerRemoteControl
