language: python
python:
  - '3.7'
dist: bionic

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y exim4 procps cpulimit ansible mailutils python3-pip
  - git clone https://github.com/ait-aecid/aminer-ansible.git roles/aminer
  - git clone https://github.com/ait-aecid/logdata-anomaly-miner
  - ln -s $PWD/logdata-anomaly-miner/source/root/usr/lib/logdata-anomaly-miner/AMinerRemoteControl $PWD/AMinerRemoteControl
  - sed -e "s+{{SOURCEDIR}}+$PWD/logdata-anomaly-miner+g" $PWD/logdata-anomaly-miner/.playbook.yml > playbook.yml

install:
  - sudo pip3 install coverage
  - sudo pip3 install fastapi
  - sudo ansible-playbook playbook.yml
  - sudo chmod +x runUnittests.sh
  - sudo chmod +x runCoverageTests.sh

script:
  - ./runUnittests.sh
  - ./runCoverageTests.sh

after_script:
  - rm $PWD/aminer-rest/AMinerRemoteControl
