[project]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.vulture]
exclude = ["unit/"]
make_whitelist = true
min_confidence = 80
paths = ["./"]
sort_by_size = true
verbose = false
